services:
  postgres-user:
    image: postgres:18
    container_name: postgres_user_connectus
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_user_connectus:/var/lib/postgresql
    ports:
      - "${POSTGRES_PORT}:5432"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 10

  flyway-user:
    container_name: flyway_user_connectus
    image: flyway/flyway
    volumes:
      - ./bdd/migrations:/flyway/sql
    depends_on:
      postgres-user:
        condition: service_healthy       # ← attend le healthcheck, pas juste le démarrage
    command: >
      -url=jdbc:postgresql://postgres-user:5432/${POSTGRES_DB}
      -schemas=public
      -user=${POSTGRES_USER}
      -password=${POSTGRES_PASSWORD}
      migrate
  

volumes:
  postgres_user_connectus: